@api = http://localhost:8080/api/v1/servicos
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJRFVzdWFyaW8iOjQsIm5vbWUiOiJndWlzIiwiZW1haWwiOiJndWlAZ21haWwuY29tIiwiaWF0IjoxNjAyNTExNjEzLCJleHAiOjE2MDI3NzA4MTN9._l54dZuFJuqH__v70lOqYRYw_H0-qxi-3y-7sMRj0_A


GET {{api}}?page=0
Accept: application/json
Authorization: Bearer {{token}}


###

POST {{api}} HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "nome": "Terraplanagem",
    "descricao": "3 anos de mercado",
    "valor": 500,
    "contato": "40028922",
    "estado": "SP",
    "cidade": "Ourinhos",
    "IDCategoriaServico": 1
}

###

PATCH  {{api}}/18 HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "nome": "Terraplanagem",
    "descricao": "4 anos de mercado",
    "valor": 600,
    "contato": "40028922",
    "estado": "SP",
    "cidade": "Ourinhos",
    "IDCategoriaServico": 1
}